apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: test-ingress
spec:
  rules:
    - host: test.com
      http:
        paths:
          - backend:
              serviceName: frontend
              servicePort: 80
            path: /